### PR TITLE
Add toJSON function

### LINKED ISSUE #3: Implement toJSON as to return simple JSON-LD object

### PR DESCRIPTION
**Pull request by alexkreidler**
I'd really appreciate any feedback you have. I haven't added tests, and I might not get to that for a bit.

Also, just a thought on ease of development for the project: you may want to consider putting the output for CJS and ESM builds in a dist/ folder in your packages. I end up having a lot of greyed out .js, .mjs, .d.ts and .js.map files in the file view of the editor after running build.

Closes #3

### CODE REVIEW

**Comment by tpluscode** [comment]
Thank you @alexkreidler. Coincidentally @martinmaillard were discussing this recently in the context of Alcaeus.

I was however reconsidering how I would like this as a built-in feature. rdfine aims to be a strongly typed interface over a dataset and a materialised JS object should reflect that. In other words, if you define and interface/class with certain accessors the JS object should have precisely those values while ignoring anything else in the dataset. This can be derived from the usage of `@property` decorators

I would also not add jsonld dependency. Note that there are no other dependencies of parsers or serialisers. Instead a `@context` can be generated only for the exact decorated properties.

**Comment by tpluscode** [comment]
About the build, I find a `dist` directory a bit of a nuisance because it forces weird imports. Would that be `import { X } from '@tpluscode/rdfine/dist'`? Completely unnecessary and hardly idiomatic.

Besides, any build artifacts are not really generated during normal development. Only when actually publishing to NPM.

**Comment by alexkreidler** [comment]
@tpluscode I understand your perspective on the jsonld dependency and also wanting to remove data that isn't accessible via an rdfine mixin. JSON-LD itself does something similar by dropping keys and values that aren't in the context (if no `@vocab` is specified).

I personally see the value of Alcaeus compared to any other libraries (namely Hercules.ts, which I also tried using for a while) as having more advanced inference features that contribute to ease of use by the developer. Namely, combining `supported<>` and plain operations and properties, along with dealing with sub/super class relationships. As I've dug into the code a bit more I see that this is powered by the expressiveness of clownface and how you've designed mixins. I think all the work you've done with generating the vocabularies to make everything strongly typed is great. 

I do actually have a question about the strong typing, which maybe I should put in a new issue to add more details. I fetch a resource with `loadResource`, which is my `EntryPoint`. If I use `//@ts-ignore`, I can write `resource.title`, which uses the `DocumentedResource` mixin, but I'm a little stumped as to how to either assert or convert the resource into that interface so I can use the benefits of typing. Maybe I just overlooked something in the docs?

I'm working on my own linked-data frontend library, Loqu, where users provide an IRI and a JSON-LD frame, which then structures the data the way they want, optionally eliminating data they don't need, and passes it to their code or frontend web components. However in this situation they wouldn't be dealing with rdfine directly and wouldn't go through the process of generating typescript defintions for their vocabularies.

When you mention "Instead a @context can be generated only for the exact decorated properties," that makes sense in a certain way, but also has limitations:
- Only the nodes/links in the graph that are properly generated as rdfine mixin classes and property decorators get output, even if the node itself has more data. Users who don't necessarily want to generate TS definitions or write classes just to access their data will be left out. Users who just want to use Alcaeus for the nice inference features will then have a higher burden to do so because they'd be required to implement rdfine classes. 
- It seems to me you'd generate a `@context` but still use a JS Proxy. This means that debugging is more difficult (console.log, etc), along with iterating through the data. It's just less transparent. A JS object makes more sense to me.

My perspective is that outputting a regular Javascript object in JSON-LD format is a good option to provide. Of course, you can encourage people to write mixins and use that pattern but I think this is a key feature.

Of course, I can get my library to still work with rdfine, just by moving this `toJSON` function into my library itself. The question is whether you want to provide that option to other users. I personally have found `toJSON` to be immensely helpful in debugging what I'm doing with Alcaeus.

I do understand the dependency issue, so I'd be happy to move `jsonld` to [`optional` or `peerDependencies`](https://classic.yarnpkg.com/en/docs/dependency-types/), and just throw an error if a user tries to call `toJSON` without having `jsonld` installed.

Also, regarding the `dist/` folder suggestion: yes the build artifacts aren't usually generated during isolated development. But since I'm using `yarn link` to work on my own library, which depends on `alcaeus` and `rdfine` which I work on the same time, I have to run `yarn compile` every once in a while, which does output the artifacts.

Also, you can set the `main`, `module`, `types` and any other relevant keys in `package.json` to `dist/index.js` and then the imports will work as usual from the top level. The same also works with the `exports` key. Many popular packages do this: [redux](https://github.com/reduxjs/redux/blob/3cf3b0f48c4093aaa094eedb11efa8656e9b0309/package.json#L26-L29), [tsdx starter tool](https://github.com/formium/tsdx#npm-run-build-or-yarn-build). I personally like `dist/{cjs,esm,types}/index.{.js,.mjs,.d.ts}`. But it's a preference of course and it's not a key issue.

Thanks for all your work on these two great projects!

**Comment by tpluscode** [comment]
Wow, thanks for this lengthy comment.

In general I dislike JSON-LD personally. It is quite unpredictable if generated programmatically. I only value it for going from plain JSON to RDF by adding a context etc. Otherwise the result is too volatile to be useful. The early versions of Alcaeus were trying to smash the resource representation into JSON-LD and it was not only a total pain but also hindered extensibility because the entire RDF/JS dataset is discarded in the process.

>  but I'm a little stumped as to how to either assert or convert the resource into that interface so I can use the benefits of typing. Maybe I just overlooked something in the docs?

The docs are not quite outdated since I've started building the 1.0 branch. With the soon-to-release 1.0-RC I will finally have to remedy that. It will also come with a thorough refactoring of the base hydra classes (via generated `@rdfine/hydra`). Not to mention a completely missing docs for rdfine itself. 

To answer your question however, you can either give the call a generic type argument like `Hydra.loadResource<ResourceInterface>` or simply type cast using `as ResourceInterface`, provided that you know what you expect from a given endpoint of property.

Similarly, you can call `resource.get<ResourceInterface>(uri)` to get a resource with an up-front strong typing. 

Of course those will only be hints and actual runtime objects are depending on the actual quads and mixin known to rdfine.

> However in this situation they wouldn't be dealing with rdfine directly and wouldn't go through the process of generating typescript defintions for their vocabularies.

This sounds like a goal similar to that of rdfine actually. The idea is precisely for consumers to define their expected interfaces for easy development. When packaged as a library, those can be used both on the front end as well as back end.

Again, in my experience JSON-LD framing is snake oil and it is too difficult to get right. Sometimes even impossible. This is why I started rebuilding the core of Alcaeus to what became rdfine. A core principle is to keep the single source of truth in the RDF/JS dataset. This reduces the mismatch between RDF (graph) and JSON-LD (tree) and also allows for easier integration using any RDF/JS tooling with operates on dataset/quads.

> It seems to me you'd generate a @context but still use a JS Proxy. This means that debugging is more difficult (console.log, etc), along with iterating through the data. It's just less transparent. A JS object makes more sense to me.

I agree. This is a major pain right now and debug-time option to materialise the combined mixins into a plain JS object would greatly improve the experience of developers willing to inspect a rdfine class. 

> Of course, I can get my library to still work with rdfine, just by moving this toJSON function into my library itself. The question is whether you want to provide that option to other users. I personally have found toJSON to be immensely helpful in debugging what I'm doing with Alcaeus.

Not in the proposed form, but I definitely still need this too and will start working on this soon.

Let me close this PR right now and let's move back to the issue itself where I will elaborate on my idea with some example and we shall work on a satisfactory end result 🤝 

---

Finally yes, I'm aware of the optional `package.json` keys but only those for main modules are really supported. While node now brings in the new `exports` key, it is not widely supported by webpack et.al. ;)

**Comment by alexkreidler** [comment]
Thanks for your thoughts, much appreciated. I look forward to future updates!

**Pull request closed without merging**
